[project]
name = "dns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dnspython>=2.7.0",
    "pyinstaller>=6.14.2",
    "pywin32>=311",
    "ttkbootstrap>=1.14.0",
]
